modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/Stoutscientist/XPFromHarvest/issues"
[[mods]]
modId = "xpfromharvest"
version = "1.2.4"
displayName = "XP From Harvest Reworked"
displayURL = "https://modrinth.com/mod/xp-from-harvest-reworked"
logoFile="logo.png"
authors = "RealGecko, Stoutscientist, UplinkPhobia"
description = '''
Get XP from harevsting crops!
'''
[[dependencies.xpfromharvest]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xpfromharvest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21,)"
ordering = "NONE"
side = "BOTH"
